### ISSUE TITLE
"Unknown error occurred" when trying to login

### ISSUE THREAD

**Issue by leolazz** [ZacheryThomas/homeassistant-smartrent#12]
After restarting and updating home assistant I am getting "Unknown error occurred" when trying to login. I have tried reloading and reinstall the integration with no success.

**Comment by ZacheryThomas** [comment]
Hi! I haven't seen that error before.

We could try enabling more logging in `homeassistant` to see if the `smartrent` integration produces meaningful output. You should be able to add these lines to `configuration.yaml` and then restarting your `homeassistant` instance.
```yaml
logger:
  default: warning
  logs:
    custom_components.smartrent: info
    smartrent: info
```

Also shouldn't really matter that much, but what version of `homeassistant-smartrent` are you running?
