### ISSUE TITLE
Changing Thermostat Mode

### ISSUE THREAD

**Issue by snepple** [ZacheryThomas/homeassistant-smartrent#3]
It appears that the SmartRent API is being called to change the Thermostat mode to “Cool”.  This is happening repeatedly and without the temp or mode being changed in Home Assistant.  I have not found any corresponding information in the Home Assistant log.

**Comment by ZacheryThomas** [comment]
Can you try adding this config to the bottom of your homeassistant `configuration.yaml` and then restarting your HA instance?:

```yaml
...
logger:
  default: warning
  logs:
    custom_components.smartrent: debug
    smartrent: debug
```

This should allow us to get some more logs out of the smartrent integration.

If the issue happens again you can try sending the logs to me and I can try to figure out whats happening.
